{{- if .Values.backstage.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rca-app.fullname" . }}-backstage
  labels:
    {{- include "rca-app.labels" . | nindent 4 }}
    component: backstage
spec:
  type: {{ .Values.backstage.service.type }}
  ports:
    - port: {{ .Values.backstage.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "rca-app.selectorLabels" . | nindent 4 }}
    component: backstage
{{- end }}
