apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rca-app.fullname" . }}-common
  labels:
    {{- include "rca-app.labels" . | nindent 4 }}
type: Opaque
data:
  rca-api-key: {{ .Values.global.rcaApiKey | b64enc | quote }}
  postgres-password: {{ .Values.backstage.postgres.password | b64enc | quote }}
