{{- if .Values.postgres.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rca-app.fullname" . }}-postgres
  labels:
    {{- include "rca-app.labels" . | nindent 4 }}
    component: postgres
spec:
  selector:
    matchLabels:
      {{- include "rca-app.selectorLabels" . | nindent 6 }}
      component: postgres
  template:
    metadata:
      labels:
        {{- include "rca-app.selectorLabels" . | nindent 8 }}
        component: postgres
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgres.image }}
          env:
            - name: POSTGRES_USER
              value: {{ .Values.backstage.postgres.user | quote }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "rca-app.fullname" . }}-common
                  key: postgres-password
            - name: POSTGRES_DB
              value: {{ .Values.backstage.postgres.database | quote }}
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          {{- if .Values.postgres.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "rca-app.fullname" . }}-postgres
          {{- else }}
          emptyDir: {}
          {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backstage.postgres.host }}
  labels:
    {{- include "rca-app.labels" . | nindent 4 }}
    component: postgres
spec:
  ports:
    - port: 5432
  selector:
    {{- include "rca-app.selectorLabels" . | nindent 4 }}
    component: postgres
{{- if .Values.postgres.persistence.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "rca-app.fullname" . }}-postgres
  labels:
    {{- include "rca-app.labels" . | nindent 4 }}
    component: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.persistence.size | quote }}
{{- end }}
{{- end }}
