{{- if .Values.prometheus.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rca-app.fullname" . }}-prometheus
  labels:
    {{- include "rca-app.labels" . | nindent 4 }}
    component: prometheus
spec:
  selector:
    matchLabels:
      {{- include "rca-app.selectorLabels" . | nindent 6 }}
      component: prometheus
  template:
    metadata:
      labels:
        {{- include "rca-app.selectorLabels" . | nindent 8 }}
        component: prometheus
    spec:
      containers:
        - name: prometheus
          image: {{ .Values.prometheus.image }}
          command:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
            - '--web.enable-remote-write-receiver'
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: data
              mountPath: /prometheus
            - name: config
              mountPath: /etc/prometheus
      volumes:
        - name: data
          {{- if .Values.prometheus.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "rca-app.fullname" . }}-prometheus
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: config
          configMap:
            name: {{ include "rca-app.fullname" . }}-prometheus-config
---
apiVersion: v1
kind: Service
metadata:
  name: rca-app-prometheus
  labels:
    {{- include "rca-app.labels" . | nindent 4 }}
    component: prometheus
spec:
  ports:
    - port: 9090
  selector:
    {{- include "rca-app.selectorLabels" . | nindent 4 }}
    component: prometheus
{{- if .Values.prometheus.persistence.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "rca-app.fullname" . }}-prometheus
  labels:
    {{- include "rca-app.labels" . | nindent 4 }}
    component: prometheus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.prometheus.persistence.size | quote }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rca-app.fullname" . }}-prometheus-config
  labels:
    {{- include "rca-app.labels" . | nindent 4 }}
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'rca-app-server'
        static_configs:
          - targets: ['{{ include "rca-app.fullname" . }}-server:8080']
      - job_name: 'rca-node-agent'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_component]
            action: keep
            regex: node-agent
{{- end }}
