apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rca-server-sm
  namespace: observability
  labels:
    team: observability
spec:
  selector:
    matchLabels:
      app: rca-server
  namespaceSelector:
    matchNames:
      - observability
  endpoints:
    - port: 8080
      path: /metrics
      interval: 30s
      honorLabels: true
