apiVersion: v1
kind: Service
metadata:
  name: cluster-agent
  namespace: observability
  labels:
    app: cluster-agent
spec:
  selector:
    app: cluster-agent
  ports:
  - port: 80
    targetPort: 9100
    name: http