apiVersion: apps/v1
kind: Deployment
metadata:
  name: rca-server
  namespace: observability
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rca-server
  template:
    metadata:
      labels:
        app: rca-server
    spec:
      containers:
        - name: rca-server
          image: ghcr.io/ravicb765/rca-app/server:latest
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "1"
              memory: "512Mi"