apiVersion: v1
kind: Service
metadata:
  name: rca-app-server
  namespace: observability
  labels:
    app: rca-app-server
spec:
  selector:
    app: rca-app-server
  ports:
  - port: 8080
    targetPort: 8080
    name: http